### ISSUE TITLE
Curation: update DGP names

### ISSUE THREAD

**Issue by katiestahl** [bridge2ai/b2ai-standards-registry#159]
As a data manager I want to see attributes for each data standard that include a list of data generators that have adopted my standard, so that I can...

Work required:
- Update the DGP names in the Organization table
- Need clarification from @caufieldjh do we need a new slot for the Organization table to accomplish this? Or should we leverage the subclass property and add new entries for each standard?

**Comment by caufieldjh** [comment]
> Update the DGP names in the Organization table

This was accomplished in #141 , e.g., this is the new entry for Salutogenesis:
```yaml
  - id: B2AI_ORG:114
    name: Salutogenesis Grand Challenge
    subclass_of:
      - B2AI_ORG:106
    category: B2AI_ORG:Organization
    description: >-
      The Bridge2AI Salutogenesis Grand Challenge, also known as the Artificial
      Intelligence Ready and Equitable Atlas for Diabetes Insights project
      (AI-READI).
    url: https://aireadi.org/

    contributor_name: Harry Caufield
    contributor_github_name: caufieldjh
    contributor_orcid: "ORCID:0000-0001-5705-7831"
```

I kept the id for each GC unchanged.
