### ISSUE TITLE
Curation: add related tools/standards

### ISSUE THREAD

**Issue by katiestahl** [bridge2ai/b2ai-standards-registry#160]
As a tool developer I want to see attributes for each data standard that include a list of tools associated with a standard, so that I can check if I need to develop a new tool addressing certain standard needs

Work required:
- add new slot for DataStandardOrTool called relates_to (? or something better if possible) and have it be a STRING_LIST column type. Add ids for related standards/tools. (This is very similar to the work done for adding has_training_resource - see below)

ex has_training_resource work:
new slot in schema: https://github.com/bridge2ai/standards-schemas/pull/39
curation for this repo: https://github.com/bridge2ai/b2ai-standards-registry/pull/131

Can we maybe leverage this? https://github.com/bridge2ai/standards-schemas/pull/14

**Comment by caufieldjh** [comment]
Yep, looks like a job for that `related_to` slot - no new slot needed.
So this is primarily a curation task.
It's a very general slot name, though, so we'll need to document that a `related_to` relationship could represent many different types of connections, from "this tool was developed to implement this standard" to "this tool is what is generally used to produce data following this standard, though it isn't really intended for that purpose"

**Comment by korikuzma** [comment]
@caufieldjh can you help confirm that I'm understanding this correctly.

I will be looking in [DataStandardOrTool.yaml](https://github.com/bridge2ai/b2ai-standards-registry/blob/main/src/data/DataStandardOrTool.yaml) where `category` is a `DataStandard` or `BiomedicalStandard`. I will then search in [DataStandardOrTool.yaml](https://github.com/bridge2ai/b2ai-standards-registry/blob/main/src/data/DataStandardOrTool.yaml) to find instances where `category` is a `SoftwareOrTool` and add this to `related_to` in the standard. 

For example,

```yaml
  - id: B2AI_STANDARD:130
    name: GA4GH
    category: B2AI_STANDARD:BiomedicalStandard
    description: GA4GH metadata model
    concerns_data_topic:
      - B2AI_TOPIC:13
    has_relevant_organization:
      - B2AI_ORG:34
    purpose_detail:
      The metadata model for GA4GH, an international coalition of both
      public and private interested parties, formed to enable the sharing of genomic
      and clinical data.
    is_open: true
    requires_registration: false
    formal_specification: https://github.com/ga4gh-metadata/metadata-schemas
    contributor_name: Harry Caufield
    contributor_github_name: caufieldjh
    contributor_orcid: ORCID:0000-0001-5705-7831
    ### ADDED SLOT ###
    related_to:  ### ADDED SLOT ###
        - B2AI_STANDARD:830
  - id: B2AI_STANDARD:830
    name: TES
    category: B2AI_STANDARD:SoftwareOrTool
    description: Task Execution Service
    concerns_data_topic:
      - B2AI_TOPIC:5
    has_relevant_organization:
      - B2AI_ORG:34
    purpose_detail:
      standardized schema and API for describing and executing batch execution
      tasks
    is_open: true
    requires_registration: false
    url: https://ga4gh.github.io/task-execution-schemas/docs/
    contributor_name: Harry Caufield
    contributor_github_name: caufieldjh
    contributor_orcid: ORCID:0000-0001-5705-7831

```
