### ISSUE TITLE
Curation: schema specification

### ISSUE THREAD

**Issue by katiestahl** [bridge2ai/b2ai-standards-registry#162]
As a PI I want to see attributes for each data standard that include a schema specification of the standard, so that I can visualize the schema and explore the standard requirements for sequencing data and downsltream levels of analysis, so that I can determine what type of genomic variant calls information is required by this standard

Going to need input from @AmyHeiser or @caufieldjh on this one.. I have no idea what details to add here to help tell a developer what they need to do for this task

**Comment by caufieldjh** [comment]
I don't think this goal is currently feasible to the extent that we'd like.
Under ideal conditions, most of the schemas we've indexed would have some kind of formal definition, like the [RDF schema](https://www.w3.org/TR/rdf-schema/) or [BIDS](https://github.com/bids-standard/bids-specification/tree/master/src/schema). That still isn't as computable as it could be, but it's enough to clearly state what each field should look like, how we can visualize the whole thing, and so on.
But most of our schemas don't have anything like that - and when they do, it may be in any number of different formats and levels of detail.

What we _can_ do is to define the types and structures of data a standard interacts with, and we have much of what we need to do that already. With BIDs, for example, there's an entry in the DataSubstrate table for this type of data (B2AI_SUBSTRATE:3):
```yaml
  - id: B2AI_SUBSTRATE:3
    name: BIDS
    subclass_of:
      - B2AI_SUBSTRATE:19
      - B2AI_SUBSTRATE:49
    related_to:
      - B2AI_STANDARD:33
    metadata_storage:
      - JSON
    category: B2AI_SUBSTRATE:DataSubstrate
    description: Data conforming to the Brain Imaging Data Structure (BIDS).
```

It's `related_to` the BIDS standard (B2AI_STANDARD:33), so that's saying "data of this type can be handled by this standard".
The subclass relationships are helpful here, since it's telling me that one parent is B2AI_SUBSTRATE:19 ("Image") because that's one kind of thing BIDS represents.

So if we wanted to visualize this or make the data to standard relationships more navigable, showing the hierarchy of DataSubstrate types and annotating with their connections to standards may be a good start.
