### ISSUE TITLE
Process issue script: provided `description` should go in `purpose_detail`

### ISSUE THREAD

**Issue by caufieldjh** [bridge2ai/b2ai-standards-registry#204]
Minor detail in processing new entity issues:
The form has a Description field, which is fine, but `description` in the data tables is used more like an "extended name" field while the more verbose description goes in `purpose_detail`.
So the contents of the Description in the form should probably get written to `purpose_detail` in the generated PR.

Could also just ask the submitter to provide name, description, *and* purpose_detail. 

Example:
```yaml
- id: B2AI_STANDARD:890
  category: B2AI_STANDARD:BiomedicalStandard
  name: RadElement
  description: RadElement Common Data Elements (CDEs) for Radiology
  purpose_detail: A set of common data elements for radiology research.
```
