### ISSUE TITLE
Use Absolute imports + move script

### ISSUE THREAD

**Issue by Krt-11** [bridge2ai/b2ai-standards-registry#274]
Using internal imports in a script like this may also suggest it (process_issue.py) should just be part of the main module.
That is, this file could be moved to the root `/scripts` or `/src`.
Then the corresponding workflow would just need to be told to run the relevant stage(s) from the project directory with `working-directory: src` or similar, or like in https://github.com/bridge2ai/b2ai-standards-registry/blob/main/.github/workflows/new_entity_pr.yml this could be:
```yaml
...
      - name: Process the issue
        id: process_issue
        run: poetry run python process_issue.py --github
        working-directory: src/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
```
And in `process_issue.py` you can just absolute import the `format_yaml_file` method from where it is in `scripts`

_Originally posted by @caufieldjh in https://github.com/bridge2ai/b2ai-standards-registry/pull/266#discussion_r2038386858_
